In [16]:
import pandas as pd
df=pd.read_csv("Downloads/marketing_campaign.csv",sep="\t")
print("This is the Marketing campaign (Customer Personality Analysis) csv file:")
print(df.shape)
print(df.head())

print(df.isnull())

print("Before removing duplicate rows:", df.shape)
df = df.drop_duplicates()
print("After removing duplicate rows:", df.shape)

print("Standardize 'Education' column:")
df['Education'] = df['Education'].str.strip().str.title()

print("Converting Dt_Customer to datetime:")
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], format='%d-%m-%Y')

print("Renameing column headers to be clean and uniform:")
df.columns = df.columns.str.lower().str.replace(" ", "_")
print(df.columns)

print("Checking and fixing data types:")
df['year_birth'] = df['year_birth'].astype(int)
df['income'] = df['income'].astype(float)

df.to_csv("marketing_campaign_cleaned.csv", index=False)
print("FINAL DATASET VIEW.")
print(df.head())

This is the Marketing campaign (Customer Personality Analysis) csv file:
(2240, 29)
     ID  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0  5524        1957  Graduation         Single  58138.0        0         0
1  2174        1954  Graduation         Single  46344.0        1         1
2  4141        1965  Graduation       Together  71613.0        0         0
3  6182        1984  Graduation       Together  26646.0        1         0
4  5324        1981         PhD        Married  58293.0        1         0

  Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  AcceptedCmp3  \
0  04-09-2012       58       635  ...                  7             0
1  08-03-2014       38        11  ...                  5             0
2  21-08-2013       26       426  ...                  4             0
3  10-02-2014       26        11  ...                  6             0
4  19-01-2014       94       173  ...                  5             0

   AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
0             0             0             0             0         0
1             0             0             0             0         0
2             0             0             0             0         0
3             0             0             0             0         0
4             0             0             0             0         0

   Z_CostContact  Z_Revenue  Response
0              3         11         1
1              3         11         0
2              3         11         0
3              3         11         0
4              3         11         0

[5 rows x 29 columns]
         ID  Year_Birth  Education  Marital_Status  Income  Kidhome  Teenhome  \
0     False       False      False           False   False    False     False
1     False       False      False           False   False    False     False
2     False       False      False           False   False    False     False
3     False       False      False           False   False    False     False
4     False       False      False           False   False    False     False
...     ...         ...        ...             ...     ...      ...       ...
2235  False       False      False           False   False    False     False
2236  False       False      False           False   False    False     False
2237  False       False      False           False   False    False     False
2238  False       False      False           False   False    False     False
2239  False       False      False           False   False    False     False

      Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  AcceptedCmp3  \
0           False    False     False  ...              False         False
1           False    False     False  ...              False         False
2           False    False     False  ...              False         False
3           False    False     False  ...              False         False
4           False    False     False  ...              False         False
...           ...      ...       ...  ...                ...           ...
2235        False    False     False  ...              False         False
2236        False    False     False  ...              False         False
2237        False    False     False  ...              False         False
2238        False    False     False  ...              False         False
2239        False    False     False  ...              False         False

      AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
0            False         False         False         False     False
1            False         False         False         False     False
2            False         False         False         False     False
3            False         False         False         False     False
4            False         False         False         False     False
...            ...           ...           ...           ...       ...
2235         False         False         False         False     False
2236         False         False         False         False     False
2237         False         False         False         False     False
2238         False         False         False         False     False
2239         False         False         False         False     False

      Z_CostContact  Z_Revenue  Response
0             False      False     False
1             False      False     False
2             False      False     False
3             False      False     False
4             False      False     False
...             ...        ...       ...
2235          False      False     False
2236          False      False     False
2237          False      False     False
2238          False      False     False
2239          False      False     False

[2240 rows x 29 columns]
Before removing duplicate rows: (2240, 29)
After removing duplicate rows: (2240, 29)
Standardize 'Education' column:
Converting Dt_Customer to datetime:
Renameing column headers to be clean and uniform:
Index(['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome',
       'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits',
       'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts',
       'mntgoldprods', 'numdealspurchases', 'numwebpurchases',
       'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth',
       'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1',
       'acceptedcmp2', 'complain', 'z_costcontact', 'z_revenue', 'response'],
      dtype='object')
Checking and fixing data types:
FINAL DATASET VIEW.
     id  year_birth   education marital_status   income  kidhome  teenhome  \
0  5524        1957  Graduation         Single  58138.0        0         0
1  2174        1954  Graduation         Single  46344.0        1         1
2  4141        1965  Graduation       Together  71613.0        0         0
3  6182        1984  Graduation       Together  26646.0        1         0
4  5324        1981         Phd        Married  58293.0        1         0

  dt_customer  recency  mntwines  ...  numwebvisitsmonth  acceptedcmp3  \
0  2012-09-04       58       635  ...                  7             0
1  2014-03-08       38        11  ...                  5             0
2  2013-08-21       26       426  ...                  4             0
3  2014-02-10       26        11  ...                  6             0
4  2014-01-19       94       173  ...                  5             0

   acceptedcmp4  acceptedcmp5  acceptedcmp1  acceptedcmp2  complain  \
0             0             0             0             0         0
1             0             0             0             0         0
2             0             0             0             0         0
3             0             0             0             0         0
4             0             0             0             0         0

   z_costcontact  z_revenue  response
0              3         11         1
1              3         11         0
2              3         11         0
3              3         11         0
4              3         11         0

[5 rows x 29 columns]